### ISSUE TITLE
TODO. 1/3/17

### ISSUE THREAD

**Issue by c650** [c650/irc-bot-framework#6]
- [x] HTTP Post
- [x] API calls over HTTPS
- [x] Bot Metadata
	- [x] Status Command
	* **Should the Bot object be globally accessible?** Nope. Instead, we can just pass a Bot* to any command that needs it.
- [x] Make the socket connections NON_BLOCKING
- [x] Make admin/ignore more robust by switching to an internal hostmask format.

**Comment by c650** [comment]
HTTP Post remains untested but I'm not really using it and it's not actually a part of the bot...
